# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wenfeng
email: wenfengzhuo@gmail.com
description: >
  Random thoughts and Key learnings
logo: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wenfengzhuo.github.io" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage

name: 'Wenfeng'
bio: >
  Keep Learning!
author_image: ""
twitter_username: 
github_username:

# Google Analytics
analytics_id: "UA-128750316-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
